name = "SimpleMotion"
license = "MIT"
licenselink = "https://github.com/simplemotion/simplemotion.github.io/blob/main/LICENSE"
description = "Dark minimalist theme for SimpleMotion."
tags = ["minimal", "dark", "responsive", "company"]
min_version = "0.120.0"

[author]
  name = "SimpleMotion.Global"
  homepage = "https://simplemotion.github.io"
